// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NeuroTradeAPI;
using System;

namespace NeuroTradeAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20171210192516_Candles' time is required")]
    partial class Candlestimeisrequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("NeuroTradeAPI.Entities.Algorithm", b =>
                {
                    b.Property<int>("AlgorithmId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Path");

                    b.Property<int>("UserId");

                    b.HasKey("AlgorithmId");

                    b.HasIndex("UserId");

                    b.ToTable("Algorithms");
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginTime");

                    b.Property<DateTime?>("EndTime");

                    b.Property<int>("InstrumentId");

                    b.Property<TimeSpan>("Interval");

                    b.HasKey("BatchId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.Candle", b =>
                {
                    b.Property<long>("CandleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BatchId");

                    b.Property<DateTime>("BeginTime");

                    b.Property<float>("Close");

                    b.Property<float>("High");

                    b.Property<float>("Low");

                    b.Property<float>("Open");

                    b.Property<int>("Volume");

                    b.HasKey("CandleId");

                    b.HasIndex("BatchId");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("DownloadAlias");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.TrainedModel", b =>
                {
                    b.Property<int>("TrainedModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlgorithmId");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<int>("InstrumentId");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<float>("Performance");

                    b.Property<DateTime>("TestBegin");

                    b.Property<DateTime>("TestEnd");

                    b.Property<DateTime>("TrainBegin");

                    b.Property<DateTime>("TrainEnd");

                    b.HasKey("TrainedModelId");

                    b.HasIndex("AlgorithmId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("TrainedModels");
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.Algorithm", b =>
                {
                    b.HasOne("NeuroTradeAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.Batch", b =>
                {
                    b.HasOne("NeuroTradeAPI.Entities.Instrument", "Instrument")
                        .WithMany("RelatedBatches")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.Candle", b =>
                {
                    b.HasOne("NeuroTradeAPI.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NeuroTradeAPI.Entities.TrainedModel", b =>
                {
                    b.HasOne("NeuroTradeAPI.Entities.Algorithm", "Algorithm")
                        .WithMany()
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NeuroTradeAPI.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
